#ifndef EMBATTSPOTTER_GLOBAL_H
#define EMBATTSPOTTER_GLOBAL_H


#if defined(EMBATTSPOTTER_LIBRARY)
#  define EMBATTSPOTTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EMBATTSPOTTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EMBATTSPOTTER_GLOBAL_H
